// <auto-generated />
using System;
using FinalFeliz.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FinalFeliz.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250808095345_PrimeiraMigration")]
    partial class PrimeiraMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.19");

            modelBuilder.Entity("FinalFeliz.Api.Models.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FotoPerfil")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("FinalFeliz.Api.Models.FotoLocal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("MassagistaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Url")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MassagistaId");

                    b.ToTable("FotosLocal");
                });

            modelBuilder.Entity("FinalFeliz.Api.Models.MassagemComum", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<TimeSpan>("DuracaoMassagem")
                        .HasColumnType("TEXT");

                    b.Property<int>("MassagistaId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Preco")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MassagistaId");

                    b.ToTable("MassagensComum");
                });

            modelBuilder.Entity("FinalFeliz.Api.Models.Massagista", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Endereco")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FormasPagamentos")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FotoPerfil")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Massagistas");
                });

            modelBuilder.Entity("FinalFeliz.Api.Models.ServicoPremium", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("MassagistaId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Preco")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MassagistaId");

                    b.ToTable("ServicosPremium");
                });

            modelBuilder.Entity("FinalFeliz.Api.Models.FotoLocal", b =>
                {
                    b.HasOne("FinalFeliz.Api.Models.Massagista", "Massagista")
                        .WithMany("FotosLocal")
                        .HasForeignKey("MassagistaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Massagista");
                });

            modelBuilder.Entity("FinalFeliz.Api.Models.MassagemComum", b =>
                {
                    b.HasOne("FinalFeliz.Api.Models.Massagista", "Massagista")
                        .WithMany("MassagensComum")
                        .HasForeignKey("MassagistaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Massagista");
                });

            modelBuilder.Entity("FinalFeliz.Api.Models.ServicoPremium", b =>
                {
                    b.HasOne("FinalFeliz.Api.Models.Massagista", "Massagista")
                        .WithMany("ServicosPremium")
                        .HasForeignKey("MassagistaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Massagista");
                });

            modelBuilder.Entity("FinalFeliz.Api.Models.Massagista", b =>
                {
                    b.Navigation("FotosLocal");

                    b.Navigation("MassagensComum");

                    b.Navigation("ServicosPremium");
                });
#pragma warning restore 612, 618
        }
    }
}
